INSERT INTO bands (name) VALUES
('3 Inches of Blood'),
('The 3tards'),
('11:30'),
('13 Engines'),
('54-40'),
('1755'),
('Alexisonfire'),
('Acid Test'),
('The Acorn'),
('Acoustically Inclined'),
('Ad Vielle Que Pourra'),
('AfroNubians'),
('Age of Daze'),
('Age of Electric'),
('The Agonist'),
('AIDS Wolf'),
('Air Traffic Control'),
('Akuma'),
('Alert the Medic'),
('Abandon All Ships'),
('Alias'),
('All Systems Go!'),
('Alpha Galates'),
('Alta Moda'),
('Amati Quartet'),
('Amphibious Assault'),
('Anagram'),
('André'),
('Annihilator'),
('Anonymus'),
('Anvil'),
('Anyday'),
('Apollo Ghosts'),
('Apostle of Hustle'),
('An April March'),
('April Wine'),
('Arcade Fire'),
('Arise and Ruin'),
('Arkaea'),
('Arkells'),
('Armchair Cynics'),
('Armed and Hammered'),
('Armistice'),
('The Arrogant Worms'),
('The Arrows'),
('Art of Dying'),
('Artificial Joy Club'),
('The Artist Life'),
('...as the Poets affirm'),
('Ashes of Soma'),
('At the Mercy of Inspiration'),
('Atach Tatuq'),
('Attack In Black'),
('Atomic 7'),
('Austra'),
('Avec pas d\'casque'),
('The Awkward Stage'),
('Axis of Advance'),
('Ayria'),
('Azeda Booth'),
('B2Krazy'),
('B4-4'),
('Bachman–Turner Overdrive'),
('Bad Flirt'),
('Bakunin\'s Bum'),
('The Band'),
('Banlieue Rouge'),
('Banned From Atlantis'),
('Baptized in Blood'),
('Barachois'),
('Barcelona Pavilion'),
('Barenaked Ladies'),
('Barley Bree'),
('Barney Bentall and the Legendary Hearts'),
('Barra MacNeils'),
('Barstool Prophets'),
('Bass is Base'),
('The Battered Wives'),
('The Be Good Tanyas'),
('Bear Mountain'),
('Beau Dommage'),
('Beast'),
('Bedouin Soundclash'),
('Bell Orchestre'),
('Bell Tower'),
('Bella'),
('The Belle Game'),
('The Bells'),
('Belvedere'),
('Beneath the Massacre'),
('The Besnard Lakes'),
('Bet.e & Stef'),
('Big Dirty Band'),
('Big Sugar'),
('Big Wreck'),
('Bike for Three!'),
('Billy Talent'),
('The Birthday Massacre'),
('Bison B.C.'),
('BKS'),
('The Black Halos'),
('Black Jays'),
('Black Lung Inner City Choir'),
('The Black Lungs'),
('The Black Maria'),
('Black Mountain'),
('Black Ox Orkestar'),
('Blackberry Wood'),
('Blackguard'),
('Blackie and the Rodeo Kings'),
('Blanket Barricade'),
('Blasphemy'),
('Bleeker Ridge'),
('Blessed by a Broken Heart'),
('Blinker the Star'),
('Blind Witness'),
('Blood Meridian'),
('Blue Dog Pict'),
('Blue Peter'),
('Blue Rodeo'),
('Blurtonia'),
('Bob\'s Your Uncle'),
('Bobs and Lolo'),
('Bobby Kris & The Imperials'),
('Bobby Taylor & the Vancouvers'),
('Bombs Over Providence'),
('The Boomtang Boys'),
('Bootsauce'),
('Born Dead Icons'),
('Born Ruffians'),
('La Bottine Souriante'),
('Boulevard'),
('Bourbon Tabernacle Choir'),
('Bowser and Blue'),
('The Box'),
('Boxer the Horse'),
('BOY'),
('Boys Brigade'),
('Boys Night Out'),
('Braided'),
('Braids'),
('Bran Van 3000'),
('Brandon Paris Band'),
('BrassMunk'),
('Brasse-Camarade'),
('Brasstronaut'),
('The Brat Attack'),
('Brave Belt'),
('Breach of Trust'),
('Les Breastfeeders'),
('Breeding Ground'),
('Brighton Rock'),
('Broken Social Scene'),
('The Brothers Creeggan'),
('The Brothers-in-Law'),
('Brown Brigade'),
('Bruce Peninsula'),
('Buddy Wasisname and the Other Fellers'),
('Bullmoose'),
('Bunchofuckingoofs'),
('Bündock'),
('The Burning Hell'),
('Burning Love'),
('Burnthe8track'),
('Burnt Project 1'),
('Bush'),
('Butterfinger'),
('By Divine Right'),
('CANO'),
('The Cameron Family Singers'),
('Camouflage Nights'),
('Canadian Brass'),
('Canadian Bush Party'),
('The Canadian Sweethearts'),
('Cancer Bats'),
('Candi & The Backbeat'),
('The Cape May'),
('Captain Tractor'),
('Career Suicide'),
('The Carpet Frogs'),
('The Carps'),
('The Cash Brothers'),
('Catalina'),
('Cats Can Fly'),
('Cauldron'),
('Cauterize'),
('Chalk Circle'),
('Change of Heart'),
('Chango Family'),
('Che: Chapter 127'),
('Chéri'),
('La Chicane'),
('Les Chiens'),
('Chilliwack'),
('Chimo!'),
('Chixdiggit'),
('The Choir Practice'),
('Chokehold'),
('Choke'),
('Chore'),
('Chris Brown and Kate Fenner'),
('Chromeo'),
('Chucky Danger Band'),
('City and Colour'),
('Cities in Dust'),
('Clark'),
('Clarknova'),
('Classic Albums Live'),
('The Cliks'),
('Closet Monster'),
('Closure'),
('Clumsy Lovers'),
('Code Revival'),
('Coley'),
('Collapsing Opposites'),
('The Collectors'),
('Les Colocs'),
('Comeback Kid'),
('Cone Five'),
('Coney Hatch'),
('Conjure One'),
('The Consonant C'),
('Constantines'),
('The Consumer Goods'),
('Contrived'),
('controller.controller'),
('Cookie Duster'),
('Copyright'),
('Corb Lund and the Hurtin\' Albertans'),
('Corky and the Juice Pigs'),
('Th\' Corn Gangg'),
('The Corn Sisters'),
('The Cottars'),
('Les Cousins Branchaud'),
('Cowboy Junkies'),
('Les Cowboys Fringants'),
('Crash Karma'),
('Crash Parallel'),
('Crash Test Dummies'),
('Crash Vegas'),
('Creaking Tree String Quartet'),
('The Creeping Nobodies'),
('The Creepshow'),
('The Crew-Cuts'),
('Criollo'),
('Crowbar'),
('Crush'),
('Crush Luther'),
('Cry of the Afflicted'),
('Cryptopsy'),
('Crystal Castles'),
('Cub'),
('Cuff the Duke'),
('Current Swell'),
('Cursed'),
('Cyberaktif'),
('D-Cru'),
('D.O.A.'),
('Daggermouth'),
('The Daggers'),
('Dahmer'),
('Dala'),
('Daniel Wesley'),
('Danko Jones'),
('The Danks'),
('The Darkest of the Hillside Thickets'),
('The Darling DeMaes'),
('Darlings of Chelsea'),
('Dayglo Abortions'),
('D.b.s.'),
('DD/MM/YYYY'),
('Dead Brain Cells'),
('Dead Celebrity Status'),
('Dead and Divine'),
('Dead Letter Dept.'),
('Deadly Apples'),
('The Deadly Snakes'),
('Dean Lickyer'),
('Dear Jane, I...'),
('Death Cartel'),
('The Dears'),
('Death from Above 1979'),
('Debaser'),
('Decoded Feedback'),
('The Deep Dark Woods'),
('Default'),
('The DeFranco Family'),
('Deja Voodoo'),
('Delerium'),
('Deliverance'),
('The Demics'),
('Despised Icon'),
('Despistado'),
('Destroyalldreamers'),
('Destroyer'),
('Detective Kalita'),
('The Devin Townsend Band'),
('The Diableros'),
('The Diamonds'),
('Die Mannequin'),
('Dig Circus'),
('The Dik Van Dykes'),
('The Dinner Is Ruined'),
('The Diodes'),
('Dionysos'),
('Dirty Circus'),
('District 7'),
('Do Make Say Think'),
('Doc Walker'),
('Doctor'),
('Dr. Draw'),
('Dog Day'),
('Don Vail'),
('Donkey Heart'),
('The Dope Poet Society'),
('Doubting Thomas'),
('Doug and the Slugs'),
('Doughboys'),
('Downchild Blues Band'),
('Downhere'),
('Download'),
('Down With Webster'),
('Dragon Fli Empire'),
('Dragonette'),
('The Dreadnoughts'),
('Dream Warriors'),
('Dubmatique'),
('Duchess Says'),
('The Dudes'),
('The Duhks'),
('Dunk'),
('Duplex!'),
('The D\'Urbervilles'),
('Dusted'),
('11:30'),
('Eagle & Hawk'),
('Econoline Crush'),
('Eden Ants'),
('Edward Bear'),
('Egger'),
('Eidolon'),
('Eight Seconds'),
('Eldebrock'),
('Electric Magma'),
('Electro Quarterstaff'),
('Elephant Stone'),
('Elevator'),
('The Elizabeth Shepherd Trio'),
('Elliott Brood'),
('Emerson Drive'),
('Empyria'),
('Emily Haines & the Soft Skeleton'),
('The End'),
('The English Teeth'),
('English Words'),
('Enter the Haggis'),
('Epsilon Minus'),
('Eric\'s Trip'),
('Esmerine'),
('The Essentials'),
('Esthero'),
('L\'Étranger'),
('Eudoxis'),
('Euphoria'),
('Evans Blue'),
('Evening Hymns'),
('Everyone\'s Talking'),
('The Evidence'),
('The Evaporators'),
('Exciter'),
('Exhaust'),
('The Expos'),
('54-40'),
('FM'),
('FM Static'),
('Faber Drive'),
('Fake Shark - Real Zombie!'),
('Failed States'),
('Fair Ground'),
('Farm Fresh'),
('Farrell Brothers'),
('Faunts'),
('FemBots'),
('Femme Fatale'),
('Feu Thérèse'),
('Field Day'),
('Fifth Column'),
('Figgy Duff'),
('Final Fantasy'),
('Finest Kind'),
('Finger Eleven'),
('First Words'),
('Five Man Electrical Band'),
('Flannel Jimmy'),
('The Flashing Lights'),
('The Flatliners'),
('Fludd'),
('Fly Pan Am'),
('Flybanger'),
('Flying Bulgar Klezmer Band'),
('The Flying Circus'),
('Foggy Hogtown Boys'),
('Fond of Tigers'),
('A Foot in Coldwater'),
('Forest City Lovers'),
('Forgotten Rebels'),
('Forgotten Tales'),
('Forty Foot Echo'),
('Four80East'),
('The Four Lads'),
('The Framework'),
('Fraser & DeBolt'),
('Frog Eyes'),
('Front Line Assembly'),
('Frozen Ghost'),
('Fuck the Facts'),
('Fucked Up'),
('Fun 100'),
('Furnaceface'),
('GFK'),
('Galaxie'),
('The Gandharvas'),
('Garolou'),
('Gatineau'),
('Genetic Control'),
('Les Georges Leningrad'),
('Germans'),
('Ghetto Concept'),
('The Ghost Is Dancing'),
('Ghosts of Modern Man'),
('Gigi'),
('Ginger'),
('Glass Tiger'),
('Glissandro 70'),
('Glueleg'),
('Goat Horn'),
('Gob'),
('God Made Me Funky'),
('Goddo'),
('Godspeed You! Black Emperor'),
('Go Ghetto Tiger'),
('The Golden Dogs'),
('The Good Brothers'),
('The Good Lovelies'),
('The Gorgeous'),
('Gorguts'),
('The Government'),
('Grade'),
('Gramercy Riffs'),
('Grand Analog'),
('Grand Theft Bus'),
('Grant Smith & The Power'),
('The Grapes of Wrath'),
('Great Aunt Ida'),
('Great Big Sea'),
('Great Lake Swimmers'),
('Great Speckled Bird'),
('Greek Buck'),
('Gregory Hoskins and the Stickpeople'),
('Grievous Angels'),
('GrimSkunk'),
('The Groove Kings'),
('Groovy Aardvark'),
('The Gruesomes'),
('Guerilla Welfare'),
('The Guess Who'),
('The Guthries'),
('Gypsophilia'),
('hHead'),
('Hail the Villain'),
('Half Moon Run'),
('Handsome Furs'),
('Hangedup'),
('The Hanson Brothers'),
('Hardliner'),
('Hard Rock Miners'),
('The Hardship Post'),
('Harem Scarem'),
('Harlequin'),
('Harmonium'),
('Hart-Rouge'),
('Hawk Nelson'),
('Hayden'),
('Haywire'),
('Head Hits Concrete'),
('Headpins'),
('The Headstones'),
('Hedley'),
('Helix'),
('Hello Beautiful'),
('Hello, Blue Roses'),
('Hemingway Corner'),
('Henri Fabergé and the Adorables'),
('The Hermit'),
('Hexes and Ohs'),
('Hey Ocean'),
('Hey Romeo'),
('Hey Rosetta!'),
('The Hidden Cameras'),
('The High Dials'),
('High Five Drive'),
('High Holy Days'),
('High Valley'),
('Hilotrons'),
('Hinterland'),
('Hip Club Groove'),
('Hokus Pick'),
('Hollerado'),
('Hollowick'),
('Hollowphonic'),
('Holly Cole Trio'),
('Holy Fuck'),
('The Home Team'),
('Hometown Band'),
('Honeymoon Suite'),
('Hooded Fang'),
('Hostage Life'),
('Hot Hot Heat'),
('Hot Little Rocket'),
('Hot One'),
('Hot Panda'),
('Hot Springs'),
('Hrsta'),
('Huevos Rancheros'),
('Hugh Dillon Redemption Choir'),
('Human Highway'),
('Humanifesto'),
('Hummer'),
('The Hunters'),
('Hunter Valentine'),
('Huron'),
('Hylozoists'),
('I Hate Sally'),
('I Mother Earth'),
('I Spy'),
('Ian and Sylvia'),
('Idle Eyes'),
('Idle Sons'),
('IllScarlett'),
('Images in Vogue'),
('Imaginary Cities'),
('Immaculate Machine'),
('In-Flight Safety'),
('The Inbreds'),
('Infernäl Mäjesty'),
('Infidels'),
('Intermix'),
('Into Eternity'),
('Intoxicado'),
('Ion Dissonance'),
('The Irish Rovers'),
('Ironhorse'),
('Iskra'),
('Islands'),
('Jack London & The Sparrows'),
('Jacksoul'),
('Jades'),
('Jakalope'),
('Jale'),
('Jane Vain and the Dark Matter'),
('Japandroids'),
('Jaymz Bee and the Royal Jelly Orchestra'),
('Jazzberry Ram'),
('Jeff Healey Band'),
('Jellyfishbabies'),
('Jerry Jerry and the Sons of Rhythm Orchestra'),
('Jersey'),
('Jet Set Satellite'),
('Jet Black Stare'),
('Jets Overhead'),
('Jimmy George'),
('The Jimmy Swift Band'),
('The Jitters'),
('Joel Plaskett Emergency'),
('Johnny and the Moon'),
('The Johnstones'),
('Jokers of the Scene'),
('Jolly Tambourine Man'),
('The Jolts'),
('Jon and Lee & The Checkmates'),
('Jon-Rae and the River'),
('JoSH'),
('Joydrop'),
('The Judes'),
('Judy & David'),
('July Fourth Toilet'),
('The Junction'),
('Junior Blue'),
('Junior Boys'),
('Junkhouse'),
('The Just Us'),
('KC Accidental'),
('Karkwa'),
('Kashtin'),
('Kataklysm'),
('The Kelele Brothers'),
('KEN mode'),
('Kensington Market'),
('Kepler'),
('Kermess'),
('Kevin Hearn and Thin Buckle'),
('Key Witness'),
('Kick Axe'),
('Kids on TV'),
('Kill Cheerleader'),
('Killer Bunnies'),
('Killer Dwarfs'),
('The Killjoys'),
('Kinetic Ideals'),
('King Apparatus'),
('King Cobb Steelie'),
('The King Khan & BBQ Show'),
('The Kings'),
('Kiros'),
('Kitchens & Bathrooms'),
('Kittens'),
('Kittie'),
('Klaatu'),
('Knacker'),
('Kobo Town'),
('Kon Kan'),
('The Kramdens'),
('Kubasonics'),
('Lace'),
('Ladyhawk'),
('Land of Talk'),
('Last Man Out'),
('The Latency'),
('Lava Hay'),
('Leahy'),
('Lee Harvey Osmond'),
('Left Spine Down'),
('Leigh Ashford'),
('The Lemon Bucket Orkestra'),
('Len'),
('Lesbians on Ecstasy'),
('Leslie Spit Treeo'),
('L\'Étranger'),
('Letters to Elora'),
('Library Voices'),
('Lighthouse'),
('Lightning Dust'),
('Liferuiner'),
('Lili Fatale'),
('Lillix'),
('Limblifter'),
('Lime'),
('The Lincolns'),
('Lioness'),
('Little Caesar and the Consuls'),
('Little Girls'),
('Live on Arrival'),
('LiveonRelease'),
('LMDS (also known as Les Messagers Du Son)'),
('Local Rabbits'),
('Loco Locass'),
('Lola Dutronic'),
('Longing for Dawn'),
('The Look People'),
('Lost & Profound'),
('Lost Dakotas'),
('Lotus Child'),
('Love Inc.'),
('Love and Sas'),
('Love Kills'),
('The Lovely Feathers'),
('Loverboy'),
('The Lowest of the Low'),
('Low Level Flight'),
('Luke & The Apostles'),
('Luther Wright and the Wrongs'),
('The Luyas'),
('MCJ & Cool G'),
('The MRQ'),
('MacLean & MacLean'),
('Machete Avenue'),
('Madrid'),
('Magneta Lane'),
('Maharahj'),
('Mahogany Rush'),
('The Mahones'),
('Main Source'),
('Majical Cloudz'),
('Major Maker'),
('Malajube'),
('Malhavoc'),
('Mandala'),
('Manic Drive'),
('Mannequin Depressives'),
('Manteca'),
('The Manvils'),
('Maow'),
('The Marble Index'),
('Mare'),
('Marianas Trench'),
('Marilyn\'s Vitamins'),
('The Mark Inside'),
('Martha and the Muffins'),
('Martyr'),
('Mashmakhan'),
('Masochistic Religion'),
('The Matadors'),
('Matthew Good Band'),
('Matt Mays & El Torpedo'),
('Max Webster'),
('The McDades'),
('Kate and Anna McGarrigle'),
('McKenna Mendelson Mainline'),
('McMaster & James'),
('The McRackins'),
('Me Mom & Morgentaler'),
('Mean Red Spiders'),
('Means'),
('Mecca Normal'),
('The Meligrove Band'),
('The Memories Attack'),
('Memoryhouse'),
('Memphis'),
('Men Without Hats'),
('Mercey Brothers'),
('Mercy, the Sexton'),
('Merlin'),
('Merryweather'),
('Mes Aïeux'),
('Messenjah'),
('Metalwood'),
('Metric'),
('METZ'),
('The Midway State'),
('Mindil Beach Markets'),
('Mir'),
('Miriodor'),
('Mobile'),
('Moev'),
('The Moffatts'),
('The Mohawk Lodge'),
('Moist'),
('Moneen'),
('Moneyshot'),
('MonkeyJunk'),
('Monster Truck'),
('Monster Voodoo Machine'),
('Mood Ruff'),
('The Most Serene Republic'),
('Mother Mother'),
('Motion Ensemble'),
('Mountain City Four'),
('The Mountains and the Trees'),
('Moxy'),
('Moxy Früvous'),
('Mr. Pine'),
('MSTRKRFT'),
('Mudmen'),
('The Musical Box'),
('My Darkest Days'),
('The Mynah Birds'),
('Mystery'),
('Mystery Machine'),
('Mythos'),
('NQ Arbuckle'),
('Nathan'),
('National Velvet'),
('Navet Confit'),
('Negativa'),
('NEON BLUE'),
('A Neon Rome'),
('Neufeld-Occhipinti Jazz Orchestra'),
('Neuraxis'),
('Neurosonic'),
('Neverending White Lights'),
('The New Cities'),
('New Country Rehab'),
('The New Deal'),
('The New Grand'),
('New Meanies'),
('The New Pornographers'),
('Nick Buzz'),
('Nickelback'),
('The Nils'),
('Nine Mile'),
('The Nines'),
('Ninja High School'),
('Ninjaspy'),
('No Kids'),
('No Warning'),
('Noise Unit'),
('Nomeansno'),
('Norteño'),
('A Northern Chorus'),
('Northern Lights'),
('The Northern Pikes'),
('North of America'),
('Not by Choice'),
('Novacosm'),
('Novillero'),
('Nudimension'),
('Numb'),
('Numéro#'),
('The Nylons'),
('1-Speed Bike'),
('OK Cobra'),
('Obscene Eulogy'),
('Ocean'),
('Octoberman'),
('Odds'),
('Offenbach'),
('Oh No Forest Fires'),
('Ohbijou'),
('Okoumé'),
('Old World Vulture'),
('Olenka and the Autumn Lovers'),
('Oliver Black'),
('The Olympic Symphonium'),
('One Bad Son'),
('One Hundred Dollars'),
('One to One'),
('The Organ'),
('Organized Rhyme'),
('Our Lady Peace'),
('Our Mercury'),
('Ours to Destroy'),
('Out of Your Mouth'),
('Outlaws of Ravenhurst'),
('Ox'),
('P:ano'),
('The Pack A.D.'),
('Pain For Pleasure'),
('Painted Thin'),
('Paper Lions'),
('Paper Moon'),
('The Paperbacks'),
('The Paperboys'),
('Parabelle'),
('Parachute Club'),
('Paradox'),
('Parallels'),
('Parlovr'),
('Partland Brothers'),
('A Passing Fancy'),
('La Patère Rose'),
('Patrick Watson'),
('The Paupers'),
('Payolas'),
('A Perfect Murder'),
('The Perpetrators'),
('Perth County Conspiracy'),
('The Pettit Project'),
('The Philosopher Kings'),
('Pholde'),
('Phono-Comb'),
('Picastro'),
('Pigeon Hole'),
('Piledriver'),
('Pilot Speed'),
('Pink Mountaintops'),
('Plaid Tongued Devils'),
('The Planet Smashers'),
('Plants and Animals'),
('Platinum Blonde'),
('Plumtree'),
('Pluto'),
('Po\' Girl'),
('Pocket Dwellers'),
('Pointed Sticks'),
('Poledo'),
('Pony Da Look'),
('Pony Up'),
('The Poppy Family'),
('Porkbelly Futures'),
('Prairie Oyster'),
('Precious Fathers'),
('Pretty Boy Floyd'),
('The Priddle Concern'),
('Pride Tiger'),
('Priestess'),
('Prism'),
('Project Wyze'),
('Projet Orange'),
('Propagandhi'),
('Protest the Hero'),
('The Provincial Archive'),
('Prozzäk'),
('Psyche'),
('Pukka Orchestra'),
('Pulse Ultra'),
('Punky Brüster'),
('Pure'),
('The Pursuit of Happiness'),
('Put the Rifle Down'),
('Quartette'),
('Quartetto Gelato'),
('Quebec Connection'),
('Queen City Kids'),
('Quest for Fire'),
('Quickflight'),
('Quinzy'),
('Quo Vadis'),
('The Rabid Whole'),
('Radio Radio'),
('The Raes'),
('Raggadeath'),
('Rah Rah'),
('Rainbow Butt Monkeys'),
('Raised by Swans'),
('Raising the Fawn'),
('Random Killing'),
('The Rankin Family'),
('Rascalz'),
('Rational Youth'),
('Rawlins Cross'),
('Ray Condo and His Hardrock Goners'),
('Razor'),
('Re:'),
('Recovery Child'),
('Real McKenzies'),
('The Reason'),
('Red Rider'),
('Redeye Empire'),
('Republic of Safety'),
('The Respectables'),
('Le Rêve du Diable'),
('The Reverb Syndicate'),
('Reverie Sound Revue'),
('Revised Edition'),
('The Revols'),
('Rhea\'s Obsession'),
('Rheostatics'),
('Rhinoceros'),
('Rhythm Activism'),
('Ripcordz'),
('Ripped'),
('Robin Black and the Intergalactic Rock Stars'),
('Rock Plaza Central'),
('Rockets Red Glare'),
('Ron Hawkins and the Rusty Nails'),
('Rose Chronicles'),
('Rough Trade'),
('Royal City'),
('Rubber'),
('Ruby Jean and the Thoughtful Bees'),
('The Rugrats'),
('The Rural Alberta Advantage'),
('Rush'),
('The Russian Futurists'),
('Rushden and Diamonds'),
('Rusty'),
('Ryan\'s Fancy'),
('RyanDan'),
('Rymes With Orange'),
('SNFU'),
('Sackville'),
('The Saddletramps'),
('The Sadies'),
('Saga'),
('Sagapool'),
('Said the Whale'),
('Saint Alvia'),
('The Sainte Catherines'),
('Saints & Sinners'),
('The Salads'),
('Salmonblaster'),
('The Salteens'),
('Sam Roberts Band'),
('Samba Squad'),
('Same Same'),
('Sandalspring'),
('Sandbox'),
('Sattalites'),
('Scatterheart'),
('The Scenics'),
('Sea Snakes'),
('Secret and Whisper'),
('Sect'),
('Sector Seven'),
('See Spot Run'),
('Sequester'),
('Serial Joe'),
('The Sessions'),
('Set Fire to Flames'),
('Sexual Assault'),
('Shades of Culture'),
('Shadowy Men on a Shadowy Planet'),
('Shaker'),
('Shalabi Effect'),
('Shallow North Dakota'),
('Shapes and Sizes'),
('Sharon, Lois & Bram'),
('Shaye'),
('Sheavy'),
('The Sheepdogs'),
('Sheriff'),
('Shit From Hell'),
('Shotgun & Jaybird'),
('Shoulder'),
('Shout Out Out Out Out'),
('Showbusiness Giants'),
('The Shuffle Demons'),
('Shyne Factory'),
('Sianspheric'),
('A Silver Mt. Zion'),
('Silverstein'),
('Simani'),
('Simon Caine'),
('Simple Plan'),
('Simply Saucer'),
('Siskiyou'),
('Skinny Puppy'),
('The Skitzos'),
('The Skulls'),
('Sky'),
('Skydiggers'),
('The Slakadeliqs'),
('Slaughter'),
('Slaveco.'),
('Slik Toxik'),
('Sloan'),
('Sloche'),
('Slow'),
('Slowburn'),
('Slowcoaster'),
('Small Sins'),
('The Smalls'),
('Smoother'),
('The Smugglers'),
('Snailhouse'),
('Snowblink'),
('Social Code'),
('Social Deviantz'),
('Les sœurs Boulay'),
('Sol'),
('Son'),
('Sons of Butcher'),
('Sons of Freedom'),
('Sons of Maxwell'),
('Sons of Otis'),
('SoulDecision'),
('The Sparrows'),
('A Spectre is Haunting Europe'),
('Spiral Beach'),
('Spirit of the West'),
('Splitting Adam'),
('Spring Breakup'),
('Sproll'),
('Spoons'),
('SS Cardiacs'),
('Stabilo'),
('Staggered Crossing'),
('The Stampeders'),
('The Stanfields'),
('Stars'),
('Starfield'),
('Startools'),
('State of Shock'),
('Static in Stereo'),
('Steel River'),
('Steppenwolf'),
('Stereos'),
('Stiff Valentine'),
('The Stills'),
('The Stolen Minks'),
('Stonebolt'),
('Strange Advance'),
('Strapping Young Lad'),
('Stratochief'),
('Streetheart'),
('Streetnix'),
('Stringband'),
('Stripper\'s Union'),
('The Strumbellas'),
('Stutterfly'),
('Stuck On Planet Earth'),
('Subhumans'),
('Submission Hold'),
('Sugar Jones'),
('The Sugar Shoppe'),
('The Suits XL'),
('Sum 41'),
('Sumo Cyco'),
('Sunparlour Players'),
('Sunset Rubdown'),
('The Super Friendz'),
('Supergarage'),
('Sven Gali'),
('Swallowing Shit'),
('Swan Lake'),
('Sweatshop Union'),
('Sweeney Todd'),
('Sweet Thing'),
('Swing'),
('Switchblade Valentines'),
('Swollen Members'),
('Sword'),
('Sylvie'),
('Sympathy'),
('Synæsthesia'),
('2preciious'),
('3 Inches of Blood'),
('13 Engines'),
('Taima'),
('Tanglefoot'),
('Tapps'),
('Tasseomancy'),
('TBTBT'),
('The Tea Party'),
('The Tear Garden'),
('Teenage Head'),
('Tegan and Sara'),
('Ten Second Epic'),
('Tenth of May'),
('Tetrix'),
('Theory of a Deadman'),
('Theset'),
('Thesyre'),
('These Kids Wear Crowns'),
('They Shoot Horses, Don\'t They?'),
('Thine Eyes Bleed'),
('Think About Life'),
('This Is A Standoff'),
('Thor'),
('Thornley'),
('Thousand Foot Krutch'),
('Threat Signal'),
('Three Days Grace'),
('Three Dead Trolls in a Baggie'),
('Thrush Hermit'),
('Timber Timbre'),
('Tin Foil Phoenix'),
('Tinker'),
('Today I Caught the Plague'),
('Tokyo Police Club'),
('Tom Fun Orchestra'),
('Torngat'),
('Toronto'),
('Touch and Nato'),
('The Tower of Dudes'),
('The Tragically Hip'),
('Tranby Croft'),
('Trans-X'),
('The Travellers'),
('Treble Charger'),
('The Trews'),
('A Tribe Called Red'),
('Tricky Woo'),
('Tricot Machine'),
('Trillionaire$'),
('The Tripp'),
('Tristan Psionic'),
('Triumph'),
('Les Trois Accords'),
('Trooper'),
('True Myth'),
('Tú'),
('Tudjaat'),
('Tupelo Honey'),
('Turn Off the Stars'),
('Tvangeste'),
('Two Fingers'),
('Two Hours Traffic'),
('Two-Minute Miracles'),
('Ubiquitous Synergy Seeker'),
('UHF'),
('UJ3RK5'),
('The Ugly Ducklings'),
('Uisce Beatha'),
('Uncle Seth'),
('Uncut'),
('The Undecided'),
('Unexpect'),
('The Unicorns'),
('The Unintended'),
('Unit 187'),
('The United Steel Workers of Montreal'),
('Universal Honey'),
('UnKindness Of Ravens'),
('Unravelled Broken Orchestra'),
('Urgent'),
('Uzeb'),
('Vacuity'),
('Valley of the Giants'),
('Veal'),
('The Veer Union'),
('Velvet Empire'),
('Venetian Snares'),
('Le Vent du Nord'),
('The Vermicious Knid'),
('Vilain Pingouin'),
('The Viletones'),
('The Vincent Black Shadow'),
('The Violet Archers'),
('Vincat'),
('Visible Wind'),
('vitaminsforyou'),
('Voggue'),
('Voice Industrie'),
('Voivod'),
('La Volée d\'Castors'),
('The Vulcan Dub Squad'),
('Vulgaires Machins'),
('The Wailin\' Jennys'),
('Waiting for God'),
('The Waking Eyes'),
('Walk Off the Earth'),
('The Waltons'),
('The Watchmen'),
('Water on Mars'),
('Watermen'),
('Wave'),
('We Are the City'),
('We Are Wolves'),
('The Weakerthans'),
('Wednesday'),
('Wednesday Night Heroes'),
('The Weekend'),
('Weeping Tile'),
('West End Girls'),
('The Western Investor'),
('What\'s He Building In There?'),
('White Lung'),
('White Wires'),
('Whitehorse'),
('Whitey Houston'),
('Whitfield'),
('Wide Mouth Mason'),
('Widelife'),
('Wild Strawberries'),
('Wild T and the Spirit'),
('The Wilkinsons'),
('Will Currie & The Country French'),
('The Wilsons'),
('Winnipeg\'s Most'),
('Windwalker'),
('Winston'),
('Winter Equinox'),
('Winter Gloves'),
('Winter Rose'),
('Wintersleep'),
('Wolf Parade'),
('Women'),
('Wonderful Grand Band'),
('The Wooden Sky'),
('Wooden Stars'),
('Woodhands'),
('Woodpigeon'),
('Woods of Ypres'),
('Wool on Wolves'),
('World on Edge'),
('Wyrd Sisters'),
('Yamantaka // Sonic Titan'),
('Yellow Plastic Bucket'),
('You Say Party'),
('Neil Young'),
('Young and Sexy'),
('Young Canadians'),
('Young Empires'),
('Young Galaxy'),
('Young Rival'),
('Yukon Blonde'),
('Zaraza'),
('Zébulon'),
('Zeds Dead'),
('Zekuhl'),
('Zeus'),
('Zimmers Hole'),
('The Zolas'),
('Zolty Cracker'),
('Zombie Girl'),
('Zubot and Dawson'),
('Zuckerbaby'),
('Zumpano');